apiVersion: v1
kind: Service
metadata:
    name: "myfirstk8scluster-abf6"
    labels:
        app: "myfirstk8scluster-abf6"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "myfirstk8scluster-abf6"