on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n K8SLearning -g K8SLearningbf95-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n K8SLearning --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n K8SLearning --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n K8SLearning --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: k8slearning.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/PiCalc-master" -f  "PiCalc-master/Dockerfile" -t k8slearning.azurecr.io/myfirstk8scluster:${{ github.sha }}
        docker push k8slearning.azurecr.io/myfirstk8scluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myfirstk8scluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myfirstk8scluster1c19 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myfirstk8scluster1c19`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myfirstk8scluster1c19
        container-registry-url: k8slearning.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myfirstk8scldockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: myfirstk8scluster1c19
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          k8slearning.azurecr.io/myfirstk8scluster:${{ github.sha }}
        imagepullsecrets: |
          myfirstk8scldockerauth